services:
    portainer:
        image: 'portainer/portainer-ce:latest'
        container_name: portainer
        restart: unless-stopped
        ports: 
          - 8000:8000
          - 9000:9000
          - 9443:9443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /appdata/portainer:/data
    portainer-agent:
        image: 'portainer/agent:latest'
        container_name: portainer-agent
        restart: unless-stopped
        ports:
          - "9001:9001" 
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
        depends_on:
          - portainer
        