services:
    microsoft-edge:
        container_name: msedge
        image: ich777/microsoft-edge
        restart: unless-stopped
        env-file:
          - stack.env
        ports:
            - '3030:8080'
        volumes:
            - '/appdata/msedge/custom:/opt/custom:ro'
            - '/appdata/msedge:/ms-edge'
            - '/appdata/pihole.resolv.conf:/etc/resolv.conf:ro'
            - '/etc/localtime:/etc/localtime:ro'